name: Prettier CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  prettier:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only --diff-filter=AMCR origin/${{ github.base_ref }})
          if [[ -z "$CHANGED_FILES" ]]; then
            # echo "files=" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "CHANGED_FILES<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED_FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm add --save-dev prettier

      - name: Format code with Prittier
        if: steps.changed-files.outputs.CHANGED_FILES != ''
        run: |
          CHANGED_FILES="${{ steps.changed-files.outputs.CHANGED_FILES }}"
          FILES=()
          while IFS=$'\n' read -r -d $'\n' file; do
            FILES+=("$file")
          done < <(echo "$CHANGED_FILES")
          pnpm exec prettier --write "${FILES[@]}"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply Prettier Change"
