name: "Vitest"

on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  Vitest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run Vitest
        run: pnpm test:unit

      - name: Show coverage
        uses: davelosert/vitest-coverage-report-action@v2
